workflows:
  build_arm_mac:
    name: Build for Apple silicon
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: dart pub get
      - name: Create dist
        script: mkdir dist
      - name: Compile
        script: dart compile exe bin/oghref_cmd.dart -o dist/oghref_cmd
    artifacts:
      - dist/**
