name: oghref_cmd
description: Command-line tools for reviewing decoded content of metadata
version: 1.0.0
environment:
  sdk: ^3.2.0
dependencies:
  args: ^2.4.2
  oghref_model: ^2.0.5
  dolumns: ^2.0.1
  ansix: ^0.3.1
  meta: ^1.11.0
dev_dependencies:
  lints: ^3.0.0
