name: oghref_cmd
description: Command-line tools for reviewing decoded content of metadata and JSON data export support
version: 0.1.1
repository: https://github.com/rk0cc/oghref_cmd
funding:
  - https://github.com/sponsors/rk0cc
environment:
  sdk: ^3.2.0
dependencies:
  args: ^2.4.2
  oghref_model: 2.1.2
  dolumns: ^2.0.1
  ansix: ^0.3.1
  meta: ^1.11.0
dev_dependencies:
  lints: ^3.0.0
platforms:
  linux:
  macos:
  windows:
executables:
  oghref_cmd:
