blank_issues_enabled: true
contact_links:
  - name: Report OgHref bugs
    url: https://github.com/rk0cc/oghref/issues/new/choose
    about: For any OgHref related bugs, please open new issues in OgHref's repository
